# Pull base image
FROM java:8

MAINTAINER zhaojihui "zjh527@163.com"

#Install weblogic12.13
#ADD wls12130.tar.gz /tmp/
#RUN mv /tmp/wls12130 /opt/weblogic

#ENV MW_HOME=/opt/weblogic/
#ENV JAVA_OPTIONS="-Djava.security.egd=file:/dev/./urandom"

#WORKDIR /opt/weblogic/
#RUN ./configure.sh

#RUN . $MW_HOME/wlserver/server/bin/setWLSEnv.sh
#RUN mkdir -p user_projects/domains/mydomain
#RUN cd user_projects/domains/mydomain
#RUN java $JAVA_OPTIONS -Xmx1024m -XX:MaxPermSize=256m weblogic.Server

#WORKDIR /

#EXPOSE 7001
