# Pull base image
FROM devbase

MAINTAINER zhaojihui "zjh527@163.com"

# Install JDK 8
RUN cd /tmp &&  wget --no-cookies --no-check-certificate --header "Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F;oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.tar.gz"
RUN cd /tmp && tar -xzf jdk-8u60-linux-x64.tar.gz
RUN mkdir -p /usr/lib/jvm
RUN mv /tmp/jdk1.8.0_60/ /usr/lib/jvm/java-8-oracle/
RUN cd tmp && rm -r jdk-8u60-linux-x64.tar.gz



#ADD jdk-8u51-linux-x64.gz /tmp/jdk1.8.0_60
#RUN mkdir -p /usr/lib/jvm
#RUN mv /tmp/jdk1.8.0_60/jdk1.8.0_60/ /usr/lib/jvm/java-8-oracle/

#Set Oracle JDK8 as default Java
RUN update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-8-oracle/bin/java 400
RUN update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-8-oracle/bin/javac 400

ENV JAVA_HOME /usr/lib/jvm/java-8-oracle/
